version: '3.8'

services:
  backend:
    image: your-dockerhub-user/faq-backend:latest
    container_name: faq-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: faq-db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432" 

volumes:
  pgdata:
